return function(Cgode)
    local function corner(x,r)local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 7);c.Parent=x end
    local function box(s,h)local f=Instance.new("Frame");f.BackgroundColor3=Cgode.ThemeManager.Current.Surface2;f.BorderSizePixel=0;f.Size=UDim2.new(1,0,0,h or 40);f.Parent=s.Content;corner(f);return f end
    local function b(parent,text)local x=Instance.new("TextButton");x.AutoButtonColor=false;x.Text=tostring(text or "");x.Font=Enum.Font.GothamMedium;x.TextSize=13;x.TextColor3=Cgode.ThemeManager.Current.Text;x.BackgroundColor3=Cgode.ThemeManager.Current.Surface2;x.BorderSizePixel=0;x.Parent=parent;corner(x);return x end
    local S={}
    function S:createText(text)local l=Instance.new("TextLabel");l.BackgroundTransparency=1;l.Text=tostring(text or "");l.TextColor3=Cgode.ThemeManager.Current.Muted;l.Font=Enum.Font.Gotham;l.TextSize=12;l.TextXAlignment=Enum.TextXAlignment.Left;l.Size=UDim2.new(1,0,0,25);l.Parent=self.Content;return l end
    function S:createButton(name,cb,opt)local f=box(self,40);local x=b(f,name);x.Size=UDim2.new(1,-10,1,-10);x.Position=UDim2.fromOffset(5,5);x.MouseButton1Click:Connect(function()if opt and opt.animated~=false then x.BackgroundColor3=Cgode.ThemeManager.Current.Accent;task.delay(.12,function()if x.Parent then x.BackgroundColor3=Cgode.ThemeManager.Current.Surface2 end end)end;if type(cb)=="function"then task.spawn(cb)end end);return x end
    function S:createToggle(name,default,cb)local f=box(self,40);local x=b(f,"");x.Size=UDim2.fromOffset(44,22);x.Position=UDim2.new(1,-54,.5,-11);local l=self:createText("");l.Text=name;l.Parent=f;l.Position=UDim2.fromOffset(10,0);l.Size=UDim2.new(1,-70,1,0);local v=default==true;local function r()x.BackgroundColor3=v and Cgode.ThemeManager.Current.Accent or Cgode.ThemeManager.Current.Border;x.Text=v and "✓"or""end;x.MouseButton1Click:Connect(function()v=not v;r();if cb then task.spawn(cb,v)end end);r();return {Get=function()return v end,Set=function(_,z)v=not not z;r();if cb then task.spawn(cb,v)end end} end
    function S:createSlider(name,o,cb)o=o or{};local min=o.min or 0;local max=o.max or 100;local v=o.default;if v==nil then v=o.defualt end;v=v or min;local f=box(self,58);local l=self:createText("");l.Text=name;l.Parent=f;l.Position=UDim2.fromOffset(10,0);l.Size=UDim2.new(1,-80,0,24);local val=Instance.new("TextLabel");val.BackgroundTransparency=1;val.TextColor3=Cgode.ThemeManager.Current.Muted;val.Font=Enum.Font.Gotham;val.TextSize=11;val.TextXAlignment=Enum.TextXAlignment.Right;val.Size=UDim2.fromOffset(55,24);val.Position=UDim2.new(1,-65,0,0);val.Parent=f;local bar=Instance.new("Frame");bar.BackgroundColor3=Cgode.ThemeManager.Current.Border;bar.BorderSizePixel=0;bar.Position=UDim2.fromOffset(10,34);bar.Size=UDim2.new(1,-20,0,7);bar.Parent=f;corner(bar,4);local fill=Instance.new("Frame");fill.BackgroundColor3=Cgode.ThemeManager.Current.Accent;fill.BorderSizePixel=0;fill.Size=UDim2.new();fill.Parent=bar;corner(fill,4);local hit=Instance.new("TextButton");hit.BackgroundTransparency=1;hit.Text="";hit.Size=UDim2.new(1,0,0,25);hit.Position=UDim2.fromOffset(0,-9);hit.Parent=bar;local drag=false;local step=o.step or(o.precise and .1 or 1);local function set(n,fire)n=math.max(min,math.min(max,n));n=math.floor(n/step+.5)*step;if o.precise then n=tonumber(string.format("%.4f",n))end;v=n;fill.Size=UDim2.new((n-min)/(max-min),0,1,0);val.Text=tostring(n);if fire and cb then task.spawn(cb,n)end end;local function update(x)set(min+(max-min)*math.max(0,math.min(1,(x-bar.AbsolutePosition.X)/bar.AbsoluteSize.X)),true)end;hit.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then drag=true;update(i.Position.X)end end);game:GetService("UserInputService").InputChanged:Connect(function(i)if drag and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then update(i.Position.X)end end);game:GetService("UserInputService").InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then drag=false end end);set(v,false);return {Get=function()return v end,Set=function(_,z)set(z,true)end}end
    function S:createDropdown(name,options,default,cb)local f=box(self,40);local v=default or options[1];local x=b(f,tostring(name)..": "..tostring(v or"None"));x.Size=UDim2.new(1,-10,1,-10);x.Position=UDim2.fromOffset(5,5);local popup;local function close()if popup then popup:Destroy();popup=nil end end;x.MouseButton1Click:Connect(function()if popup then close();return end;popup=Instance.new("Frame");popup.BackgroundColor3=Cgode.ThemeManager.Current.Surface;popup.BorderSizePixel=0;popup.Size=UDim2.new(1,0,0,math.min(#options*32+8,220));popup.Position=UDim2.new(0,0,1,4);popup.ZIndex=20;popup.Parent=f;corner(popup,8);for _,o in ipairs(options or{})do local q=b(popup,o);q.Size=UDim2.new(1,-8,0,28);q.Position=UDim2.fromOffset(4,4+(table.find(options,o)-1)*30);q.ZIndex=21;q.MouseButton1Click:Connect(function()v=o;x.Text=tostring(name)..": "..tostring(o);close();if cb then task.spawn(cb,o)end end)end end);return {Get=function()return v end,Set=function(_,z)v=z;x.Text=tostring(name)..": "..tostring(z)end,Destroy=close}end
    function S:createTextBox(name,default,cb)local f=box(self,40);local x=Instance.new("TextBox");x.BackgroundTransparency=1;x.Text=tostring(default or"");x.PlaceholderText=tostring(name or"TextBox");x.TextColor3=Cgode.ThemeManager.Current.Text;x.PlaceholderColor3=Cgode.ThemeManager.Current.Muted;x.Font=Enum.Font.Gotham;x.TextSize=12;x.ClearTextOnFocus=false;x.Size=UDim2.new(1,-20,1,0);x.Position=UDim2.fromOffset(10,0);x.Parent=f;x.FocusLost:Connect(function()if cb then task.spawn(cb,x.Text)end end);return {getText=function()return x.Text end,GetText=function()return x.Text end,clearText=function()x.Text=""end,ClearText=function()x.Text=""end,setText=function(_,z)x.Text=tostring(z)end,SetText=function(_,z)x.Text=tostring(z)end}end
    function S:createKeyBind(name,default,cb)local f=box(self,40);local x=b(f,"");x.Size=UDim2.new(1,-10,1,-10);x.Position=UDim2.fromOffset(5,5);local key=default or Enum.KeyCode.RightShift;local listen=false;local function r()x.Text=tostring(name)..": "..key.Name end;r();x.MouseButton1Click:Connect(function()listen=true;x.Text=tostring(name)..": Press key..."end);game:GetService("UserInputService").InputBegan:Connect(function(i,g)if g then return end;if listen and i.KeyCode~=Enum.KeyCode.Unknown then key=i.KeyCode;listen=false;r();elseif i.KeyCode==key and cb then task.spawn(cb)end end);return {Get=function()return key end,Set=function(_,z)key=z;r()end}end
    function S:createColorPicker(name,default,cb)local f=box(self,40);local x=b(f,name or"Color");x.Size=UDim2.new(1,-10,1,-10);x.Position=UDim2.fromOffset(5,5);local colors={Color3.fromRGB(72,122,255),Color3.fromRGB(80,190,130),Color3.fromRGB(235,90,90),Color3.fromRGB(180,90,230),Color3.fromRGB(245,170,60)};local i=1;local c=default or colors[1];x.BackgroundColor3=c;x.MouseButton1Click:Connect(function()i=i%#colors+1;c=colors[i];x.BackgroundColor3=c;if cb then task.spawn(cb,c)end end);return {Get=function()return c end,Set=function(_,z)c=z;x.BackgroundColor3=z;if cb then task.spawn(cb,z)end end}end
    return S
end
