local CgodeUI=require(game.ReplicatedStorage.CgodeUI.CgodeUI)
local ui=CgodeUI:CreateWindow({Title="Cgode UI",Theme="Light",Size=UDim2.fromOffset(780,520)})
local tab=ui:CreateTab("Controls")
local section=tab:AddSection("Basics")
section:AddButton("Button",function() ui:Notify({Title="Clicked",Message="The button works."}) end)
section:AddToggle("Enabled",true,function(v) ui:Notify({Title="Toggle",Message=tostring(v)}) end)
section:AddSlider("Volume",0,100,60,function(v) end,5)
section:AddDropdown("Mode",{"Balanced","Performance","Quiet"},"Balanced",function(v) end)
section:AddTextbox("Enter text","",function(v) print(v) end)
local advanced=ui:CreateTab("Advanced")
local s=advanced:AddSection("Tools")
s:AddStepper("Count",0,50,5,1,function(v) print(v) end)
s:AddProgress(.65)
s:AddEmptyState("Ready","Cgode UI is running with responsive controls.")
