on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24.15.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source files
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install node packages
      run: |-
        cd ./.github/vape-bundler
        npm i

    - name: Configure bundler
      run: |-
        cp ./.github/workflows/workflowConfig.json ./.github/vape-bundler/config.json

    - name: Run Bundler
      run: |-
        node ./.github/vape-bundler/index.js prod

    - name: Commit compiled output
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add VapeCompiled
        git diff --cached --quiet && exit 0
        git commit -m "Update compiled files"
        git push
